### ISSUE TITLE
Add to F-Droid.org

### ISSUE THREAD

**Issue by BoBeR182** [DaylightingSociety/WhereAreTheEyes#1]
https://f-droid.org/

F-Droid is an installable catalogue of FOSS (Free and Open Source Software) applications for the Android platform.

**Comment by edouard-lopez** [comment]
That's was one of my first actions to see if it was on F-droid to see the openness of the project (missing=not good), then check I went to github and was relieved to see the project here.

**Comment by milo-trujillo** [comment]
Definitely a good next step. We didn't have this repo set up until yesterday, so F-Droid was not previously an option. I'm hoping to get us on F-Droid in the next day or two.

**Comment by milo-trujillo** [comment]
Alright, clearly it's taking more than a day or two, but we're still hoping to be up in a few more days. Here's a status update:

F-Droid requires building our app from source. Building the app requires an API key to allow the app to download data from MapBox, which gives us the tile data to display on the map. Our API key is not in the public repository. We've been reading through legalese to see whether we're _allowed_ to publish our API key, since many services forbid this.

It appears that MapBox will permit us to publish our API key, but we are responsible for its use. To this end we're making a second API key we'll use in the public repo and for F-Droid, so that if something goes wrong we can disable the key without effecting our Play/App-store users.

Sorry this has taken so long; It's taken a while to familiarize myself with the F-Droid build process and policies and the legal situation surrounding the API keys.

**Comment by Asara** [comment]
Looks like its on F-droid.  Is that from y'all? 

Thanks!

**Comment by milo-trujillo** [comment]
Yes, it went through this morning! We'll be posting an announcement and adding a link on the downloads page later today.
