### ISSUE TITLE
Move compas completely in view

### ISSUE THREAD

**Issue by PanderMusubi** [DaylightingSociety/WhereAreTheEyes#18]
The app only shows 2/3 of the compass. Please move it down so it is completely visible.

**Comment by milo-trujillo** [comment]
This is an issue on both platforms related to drawing the scorebar over part of the map. Fixing it will involve dynamically resizing the map based on the presence of the scorebar. You are welcome to fix this yourself, it should be a relatively small patch to `MainActivity.java` on Android and `ViewController.m` on iOS. Otherwise a fix is planned, but it's low priority.

Until then, if viewing the complete compass is critical to you then you can disable the scorebar in settings.

**Comment by milo-trujillo** [comment]
Fix is complete for iOS and will be included in the next release. It will probably be fixed for Android by then, too.

**Comment by milo-trujillo** [comment]
Fix released.
