### ISSUE TITLE
Offline use

### ISSUE THREAD

**Issue by ghost** [DaylightingSociety/WhereAreTheEyes#25]
Is possible add an ability to download a particular region and see the map/camera position offline??

**Comment by milo-trujillo** [comment]
Whoops. This used to be default, but now we clear the pins each time we try to download more cameras, to support removing cameras from the map. Need to add an exception to leave the pins on if we're offline.

**Comment by erdmark** [comment]
Instead of downloading all pins every time you could add a number to each version. Every time when there is a change of pins increment version on server by one and only download new pins when version is different on the device.

**Comment by milo-trujillo** [comment]
This seems separate from the offline use issue. I agree, we should put some kind of caching in so the client doesn't re-download pins needlessly. I had a similar idea to yours, but using a hash of the pin information instead of a version number so the hash can be recalculated if something goes wrong and there's no chance of integer overflow or something.

Regarding the original issue, this should be better in the current release. The Android and iOS clients will no longer remove cameras if they are offline, allowing you to cache all the cameras for offline-browsing. Unfortunately you won't be able to fetch additional map-tiles from mapbox, so you can't scroll around the map, but it's a step in the right direction.

**Comment by milo-trujillo** [comment]
This is default behavior on iOS and Android, and has been for some time. Closing the issue.
