### ISSUE TITLE
Improve location accuracy

### ISSUE THREAD

**Issue by PanderMusubi** [DaylightingSociety/WhereAreTheEyes#26]
Accuracy is, compared to e.g. OsmAnd and other apps on Android, extremely bad. It takes a long time to get a fix. The 'here' marker moves extremely slowly to the actual location. See also https://github.com/DaylightingSociety/WhereAreTheEyes/issues/11

**Comment by milo-trujillo** [comment]
This may be a problem with MapBox, since they handle our location updates and render the 'here' marker. Hopefully a later MapBox update will fix this problem for us, but it's not a priority. Rather than focusing on improving location accuracy, we're going to improve placing pins when location is inaccurate (such as indoors, or in a city with tall buildings, where GPS cannot reach well). See issue #7 for details.
