### ISSUE TITLE
OpenStreetMap Integration

### ISSUE THREAD

**Issue by 0verk1ll** [DaylightingSociety/WhereAreTheEyes#31]
I noticed that you used maps provided by Mapbox. There is an open-source alternative to Mapbox that you might want to look into called [OpenStreetMap](https://www.openstreetmap.org/). They provide maps created by the open-source community and anyone is allowed to use their maps in their projects as long as they provide attribution (https://www.openstreetmap.org/copyright). It would be great if you could integrate with OpenStreetMap and have your entire project be open-source.

**Comment by milo-trujillo** [comment]
I believe you may be misinformed. We chose Mapbox based on [OpenStreetMap's recommendation](https://web.archive.org/web/20160312042826/http://wiki.openstreetmap.org/wiki/Tile_usage_policy). Mapbox uses the map data *from* OpenStreetMap, but provides tile data so that we aren't placing stress on the OSM servers. We already provide attribution for both OSM and Mapbox. Further, [all of the Mapbox code we use *is* open source](https://www.mapbox.com/about/open/), and we are working to more closely integrate our camera data with the [OpenStreetMap surveillance layer](https://wiki.openstreetmap.org/wiki/Key:surveillance). Please correct me if my information is wrong.
