### ISSUE TITLE
project health

### ISSUE THREAD

**Issue by elKaZe** [DaylightingSociety/WhereAreTheEyes#32]
Hello everybody, 
I've seen that there is no new version or merges, so I want to know how is going there? :D

**Comment by milo-trujillo** [comment]
Hi there! Great question, and really deserves a post on the website so more people can see. However, the short version is we've been up to:

* Social work - promoting *Where are the Eyes* online, and to particular groups like [the ones fighting FBI surveillance in Seattle](http://www.geekwire.com/2017/fearing-trump-administrations-reach-seattle-city-council-fights-fbi-spds-warrantless-surveillance-cameras/)
* Development on two not-yet-released Daylighting Society projects
* Integration with OpenStreetMap - so far this has involved writing lots of standalone scripts to test working with the OSM API, which is why you haven't seen anything pushed to GitHub

So there hasn't been much visible activity, but I promise you we're hard at work!

We can keep talking here if you have any other questions, but I'm going to close the issue so it doesn't appear as an action item.
