### ISSUE TITLE
WhereAreTheEyes stopped showing marked cameras and my location

### ISSUE THREAD

**Issue by Poomex** [DaylightingSociety/WhereAreTheEyes#33]
Hi,
I love your app and promote it with my activist friends. I use the Android version from F-Droid.  However, since around 3 days it hasn't shown anything but the map, but there is no cameras or my location marked. I also tried it on my second phone and no luck there either. I tried reinstalling but to no avail. 
This is a really bad moment, because I just shared the app on a fanpage with thousands of followers and I'm afraid they won't be able to use it and map our city.

**Comment by milo-trujillo** [comment]
Thank you for the support! It's great to hear people are promoting this!

I am unable to reproduce the problem - I just installed a fresh version of *Where are the Eyes* off F-Droid and location and camera data works fine. Can you give me some more information? What version of Android are you running? Could you be running a firewall or something else blocking access to eyes.daylightingsociety.org?

Is anybody else having this problem? Fixing it is a priority, but it's hard to know where to start if everything is running smoothly here.

**Comment by Poomex** [comment]
I have 7.1.1 on my main phone. I usually use Tor through Orbot, so I tried disableing it, connecting through another Wi-Fi and connecting through LTE. The other phone is running Marshmallow, although I only tried running it on my home Wi-Fi. 

Here are some screenshots from the main phone:

![screenshot_20170311-100447](https://cloud.githubusercontent.com/assets/21321389/23826200/e93fae06-0697-11e7-8a62-abc59983d88e.png)
![screenshot_20170311-133051](https://cloud.githubusercontent.com/assets/21321389/23826201/e946bba6-0697-11e7-8fe9-6118b37e8c7b.png)

**Comment by milo-trujillo** [comment]
*Where are the Eyes* doesn't have proxy support, so it won't run over Tor unless you make the whole device run over the SOCKS proxy. I've never tested it over a proxy, so that may cause issues for you.

However, that still doesn't explain why you're not getting data with a direct connection on Wifi or LTE, assuming you have your GPS enabled and permissions granted. My Android 7.1.1 tablet isn't having trouble, and I can't reproduce the problem in a simulator, either.

Are you able to get USB debugging output from your phone for me?

**Comment by Poomex** [comment]
Sorry for the delay, rough week ;)
Here's the logcat output:
[logcat.txt](https://github.com/DaylightingSociety/WhereAreTheEyes/files/842959/logcat.txt)

**Comment by milo-trujillo** [comment]
So I see a few interesting things in this log:

> 03-14 23:42:05.694  1452  1951 D Score   : Downloaded score data: ERROR: Invalid login
03-14 23:42:05.695  1452  1953 D GPS     : Downloading pins...
03-14 23:42:05.695  1452  1953 D GPS     : Position is null!!

The first line indicates you have an invalid username or no username set, which is fine, it will just make the map read-only.

The third line suggests GPS is disabled, or we're being blocked from accessing it somehow. We should have permission to access location data, or *Where are the Eyes* would be complaining elsewhere. This will prevent you from downloading cameras, and since Mapbox gets its location data from the same place it will prevent the map from locking on your location and displaying the blue dot.

You're absolutely sure the GPS on your devices is working correctly, and there's nothing blocking access to particular apps?

**Comment by Poomex** [comment]
I didn't turn location on, thought it was irrelevant - the pins showed up without it. Android Privacy Guard has all the location-related options set to allowed BTW. The login information is definitely correct. This never happened before, and I haven't changed any settings.

After turning location on and waiting a long time I had the blue dot, but still no pins.

And now I restarted the app after connecting to ADB and suddenly, the pins are back! Let's hope it stays that way :smile:

**Comment by milo-trujillo** [comment]
Fascinating - the pins should never show up without location, unless they were cached from back when location *was* enabled. Usually the app anonymously polls our server with an extremely rounded version of your location; enough to say "Hi, I'm in Southern Ohio, give me all the nearby cameras". Right now the location *is* irrelevant, we just give you all the cameras all the time. Once our database gets bigger though, it will help speed things up considerably.

> I restarted the app after connecting to ADB and suddenly, the pins are back!

Yeah, the app doesn't have the best handling of detecting when location is suddenly enabled, it would probably wait ten minutes before polling GPS again, glad restarting it did the trick. I'm going to open another issue for improving this exact scenario, thanks a lot for figuring this out with me!
