### ISSUE TITLE
Confirmation by same user

### ISSUE THREAD

**Issue by alcharkov** [DaylightingSociety/WhereAreTheEyes#4]
Hi, when the camera location added, then it can be confirmed by same user which adds it.

**Comment by milo-trujillo** [comment]
Can you explain what you mean? A user can both mark a camera on the map _and_ verify it's existence?

**Comment by alcharkov** [comment]
Yes, I can verify my own addition

**Comment by milo-trujillo** [comment]
I have been unable to reproduce this problem. I assume the steps are:

* Mark a new camera
* View that confirmations are at "1"
* Try to mark a new camera at the same location
* View that confirmations are now at "2"

Instead I get the expected behavior, that the new camera remains at one confirmation, and the server ignores my second mark. I am going to close this issue unless it is confirmed by another user.
