### ISSUE TITLE
Please use git tags

### ISSUE THREAD

**Issue by rugk** [DaylightingSociety/WhereAreTheEyes#42]
Please [tag](https://git-scm.com/book/en/v2/Git-Basics-Tagging) your [releases](https://help.github.com/articles/about-releases/), so they can be seen [on GitHub](https://help.github.com/articles/creating-releases/).

Also, this may help F-Droid.

**Comment by milo-trujillo** [comment]
We haven't been tagging releases since the iOS and Android version numbers are sometimes out of sync (mostly when a minor patch is released for bugs only present on one platform), and we aren't using GitHub tags for F-Droid anyway, but we could put in separate release tags for iOS and Android, like [Mapbox does](https://github.com/mapbox/mapbox-gl-native/releases).

We'll do this starting with the next release, unless the community thinks it's worth tagging retroactively. Thank you for the suggestion.

**Comment by rugk** [comment]
Yeah, nothing is wrong with tagging separate tags for Android/iOS.
