### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by n0kovo** [DaylightingSociety/WhereAreTheEyes#60]
This is an amazing project. It seems like it hasn't been actively developed for quite some time. Is the project considered abandoned?

**Comment by milo-trujillo** [comment]
> This is an amazing project

Thank you!

> Is the project considered abandoned?

More or less, yes. I'm still alive and have kept the server up and running so that the app still functions, but I've moved on to other projects and am no longer maintaining or adding features to the iOS or Android WhereAreTheEyes apps. Some reasoning below.

### What were the problems with _Where are the Eyes?_

Consumer location accuracy is low, especially on foot next to buildings, _especially_ on cheaper Android devices. Therefore, the precision of camera locations on the map varies widely, from accurate-to-the-meter to an-entire-street-off. This means Where are the Eyes works great as a social statement, "hey, look how many cameras are around you all the time!" but doesn't work for more fine-tuned purposes like "navigate a path from point A to point B while avoiding as much surveillance as possible." This could be fixed with some UI for letting the user select where to put the camera near them on the map, but it's a fair bit of work to implement, and a lot of work to make that user experience elegant and natural to use. Also, we would have needed to implement the navigation system entirely by ourselves, which was way out of scope for this project.

The user base was also small, limiting the project's impact. I love this project, and have gotten a lot of great feedback about it over the years. To really maximize its impact though, the data should be integrated into larger projects with more users. The obvious choice is adding our camera data into OpenStreetMap. Unfortunately, the OpenStreetMap team was very resistant to the idea. They want all data to be submitted to OSM directly by users, so each WhereAreTheEyes user would need an OSM account, and the WhereAreTheEyes app would add the camera data to OSM on their behalf. They would _not_ allow us to submit the camera data from the Eyes server using a single OSM account for the project. This means every user would have to de-anonymize themselves and have their OSM username associated with every camera they've marked - an idea that's unappealing to many counter-surveillance people.

Given the above two concerns, it felt like the project had hit a wall. We could work on smaller features (bug fixes, a heatmap of camera density, some gamification of camera-marking), but nothing that would fundamentally address the two big limitations of the tool.

### Are there any plans for reviving _Where are the Eyes_ or combining it with other efforts?

No plans for revival. The data is [all public](https://eyes.daylightingsociety.org/rawdata) if it can be used for a good cause. For a while the people behind _Ghost Me_, a similar project, expressed interest in inheriting this infrastructure to help jump-start some of their work, but it never came to fruition.

### What would it take to continue development?

At this point if you wanted to write a next release of _Where are the Eyes_ you'd be best off taking the general structure and writing a new app largely from scratch. The Android APIs have grown and changed a ton since 2017, making this code beyond antiquated. Apple doesn't even recommend writing apps in Objective-C anymore, and it could be re-implemented better in Swift. It was never great code to begin with: I started working on _Where are the Eyes_ when I was a Sophomore in college, and I was learning mobile app development as I went. Someone more experienced could do a _much_ better job.

###

**Comment by milo-trujillo** [comment]
I've added a slightly expanded version of the above post as [a news item on the website](https://eyes.daylightingsociety.org/), so it's more accessible than a closed GitHub issue.
