### ISSUE TITLE
Score not showing initially

### ISSUE THREAD

**Issue by senorwafflez** [DaylightingSociety/WhereAreTheEyes#8]
Setting for "Show score" had to be switched off and back on to work properly.
Might be another default value problem.

**Comment by milo-trujillo** [comment]
Yes, this is the same problem. I've tested the fix, and will close this issue when the code is accepted and we close #5. While we're at it I've changed the default to NO so users have to opt-in to having that information ever sent across a network, or showing their username on screen. Because of the bug this is current behavior as well.

**Comment by milo-trujillo** [comment]
Version 1.2 fixes the preferences problem. The default is now _not_ to show the user's score, but the Settings will correctly reflect the current state.
